### ISSUE TITLE
US5: Restart the game

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#11]
## Value Proposition

**As a** user
**I want to** restart the game
**in order to** keep on playing
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/7f045cd0-2811-4158-8a0d-55d81abe272b)

## Acceptance Criteria

- [x] When the last played card has disappeared, a 'Play again' button is shown
- [x] Clicking the button will start a new game with new random cards
      ​

## Tasks

- [x] Create a feature-branch
- [x] Update the Button-Component to make it functional (props: label text, primary/secondary, onClick)
- [x] Render the button when no cards are shown
- [x] Create the onClick function to restart the game
