### ISSUE TITLE
US6: Show hits and views

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#12]
## Value Proposition

**As a** user
**I want to** see the count of right answers and the total of views for each card
**in order to** track my success.
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/8d713b25-c92e-41c4-ad7a-7fd53c589b58)

​

## Acceptance Criteria

- [x] Each card shows an eye icon and the total amount of views (views).
- [x] Each card shows a checkmark icon and the total amount of right answers (hits).
      ​

## Tasks

- [ ] Create a feature-branch.
- [x] Modify the dummy data to have a count of hits and views.
- [x] Modify the `pickXRandomCards()` to additionally increase the number of views each time a card is selected.
- [x] Update the Card-component to show the hits and views.
