### ISSUE TITLE
US7: Implement LocalStorage

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#13]
## Value Proposition

**As a** user
**I want to** save my ratings
**in order to** start from that point the next time and not to play with learned cards (5 right answers) anymore
​

## Description

The dummy data is stored in the local storage. Increasing the number of right answers and total views will be stored and is available the next time a game is played.
​

## Acceptance Criteria

- [x] Increasing the number of right answers will be stored for the next game
- [x] Each time a card is shown the count of total views is increased
- [x] A maximum number of 5 right answers is possible
- [x] Learned cards (5 right answers) are not part of a new game

      ​

## Tasks

- [x] Create a feature-branch
- [x] Implement Local-Storage to persist the data
- [x] Modify the function handleRight to increment the count of right answers
- [x] Make sure, a new game fits only cards with less than 5 right answers
