### ISSUE TITLE
US8: Implement design

### ISSUE THREAD

**Issue by kai-franke** [Roland-Hufnagel/voc-trainer#18]
## Value Proposition

**As a** user
**I want to** experience a fresh and modern design
**in order to** enhance usability, engagement, and overall satisfaction.

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/71948045/5c7d68d9-d1cd-4cd3-b515-5ed1f28c865c)

​

## Acceptance Criteria

- [x] The `<body>` has a background of #F5F7FD
- [x] The `Header` component shows the logo of the app
- [x] The `Card` components have different primary colors (#B0C9EB, #B0E2EB, #A9EAD8). No matter how many cards are displayed during the first rendering, the same color is not repeated twice in a row.
- [x] The `show answer` button is replaced by a slider with an `arrow` icon. When the slider is clicked, it slides to the right out of the visible area of the card and shows the translation.
      ​

## Tasks

- [x] Create a new feature branch.
- [x] Change background color of `<body>` to #F5F7FD.
- [x] Add logo and shadow to `Header`.
- [x] Replace button with a slider in 'Card'. The slider gets its primary color as a prop from `Home`.
- [x] Create the CSS effect to move the slider and add this effect as `onClick` to the slider.
- [x] Create a function that sets the order of the primary colors when rendering the cards.
- [x] Install the Google fonts _Inter_ and _Cutive_ so that they can be used throughout the project.

**Comment by Roland-Hufnagel** [comment]
I like this US very much. The description shows the value at first sight. Acceptance-Criterias and tasks are clear and useful. 💪
But hard to code I think? I am looking forward to see your implementation of the card colors (never twice in a row - what happens if some cards disappear?) and to see the animation of the slider. 👍

**Comment by kai-franke** [comment]
That's a good point, which I can't answer at this time because I don't know how the cards will disappear (will they be deleted from the array or only the 'display' property will be changed?). Therefore, I have slightly modified my bold claim and added 'during the first rendering' for clarification. 😉
