### ISSUE TITLE
Add form for new vocabularies

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#20]
## Value Proposition

**As a** user
**I want to** add new vocabularies 
**in order to** expand my training

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/57e304fd-8495-4f08-a535-73f419145d8a)

​

## Acceptance Criteria

- [x] A form with two inputs-fields and a 'Add'-button is visible on the homepage
- [x] Clicking 'add' will save the new vocabulary to the localStorage
- [x] The form can't be submitted without valid inputs
      ​

## Tasks

- [x] Create a Form component with the corresponding inputs and submit button
- [x] Create a handleSubmit function that improves correct data and saves it to localStorage
- [x] Render the component at the top of homepage
