### ISSUE TITLE
Words-Page

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#23]
## Value Proposition

**As a** user
**I want to**  see all defined words
**in order to** to have a good overview.
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/c7b6ef27-248d-43db-a846-5ec4768becb6)

## Acceptance Criteria

- [x] A page shows a list of all words, that are stored in localstorage incl. views and hits

      ​

## Tasks

- [x] Create a feature-branch
- [x] Create a new page ``pages/words.js``
- [x] Lift the state up to _app.js
- [x] Pass the state as a prop to ``pages/index.js`` and to ``pages/words.js``
- [x] Render a list of all stored words in incl. views and hits in ``pages/words.js``
