### ISSUE TITLE
Edit words

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#24]
## Value Proposition

**As a** user
**I want to** be able to edit all stored words incl. hits and views
**in order to** fix typos or reset the hits and views or delete words
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/85e25332-278a-4c23-9fff-bfe5c6f6ba6b)

​

## Acceptance Criteria

- [x] Each entry in the word-list has an edit and a delete-button
- [x] Clicking 'edit' will make the entry editable
- [x] Clicking 'remove' will delete the entry directly
- [x] In Editing-mode, the edit- and remove button will disappear
- [x] In Editing-mode a save-button will save the data on click and end the editing mode
- [x] Only one entry is possible to edit at one time
      ​

## Tasks

- [x] Create a feature branch
- [x] Create a form Component for the corresponding data
- [x] Write a submit handler to update localStorageState
- [x] Render the list conditionally: Only one list-item is in 'edit-mode' or not.
