### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#25]
## Value Proposition

**As a** user
**I want to** have a navigation
**in order to** switch between the homepage and the words-page
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/5e1d4a12-4596-4c5e-91b4-1789039d4c13)

## Acceptance Criteria

- [x] A navigation is at the bottom of the page
- [x] The navigation scrolls not
- [x] One link leads to the homepage
- [x] One link leads to the words-page
- [x] One link leads to the dashboard-page
- [x] The current page link is highlighted
      ​

## Tasks

- [x] Create a feature-branch
- [x] Create a Navigation Component
- [x] Render the Navigation on each page
