### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#26]
## Value Proposition

**As a** user
**I want to**  use a dashboard
**in order to** define my personal settings

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/32ad5cb2-3836-4999-825e-0cbe611e2a3d)

​

## Acceptance Criteria

- [x] A page ``settings``shows the basic settings
- [x] Each entry can be edited
- [x] Changes apply immediately on the homepage
      ​

## Tasks

- [x] Create ``pages/dashboard``
- [x] Render conditionally the settings
- [x] Each setting can be edited by clicking an edit-button
- [x] Changes can be saved by clicking a save-button
