### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#34]
## Value Proposition

**As a** user
**I want to** edit my data using a modal window
**in order to** have a secure and modern layer when editing or deleting items
​

## Description

​

## Acceptance Criteria

- [x] The Modal fits the complete viewport even when scrolling
- [x] The Modal closes on button click and on clicking the background
- [x] The Modal renders its children 
      ​

## Tasks

- [x] Create a feature-branch
- [x] Create a Modal Component that accepts an onClose function and children as props
- [x] Create a close-button in that Modal and bind the onClose-function to.
- [x] Bind the onClose function to the background layer, too.
