### ISSUE TITLE
US1: Render a list of cards

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#4]
## Value Proposition

**As a** user
**I want to**see a set of cards
**in order to** start training them
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/25882192-beb6-4e5f-811c-08630f825b11)

​

## Acceptance Criteria

- [x] A title is displayed at the top
- [x] A list of cards is displayed
- [x] The list scrolls vertically
- [x] The header scrolls not (fixed)
      ​

## Tasks

- [x] Create feature-branch
- [x] Create example data
- [x] Create Card Component
- [x] Create List Component
- [x] Render Cards in List Component
- [x] Render List in Homepage

**Comment by Roland-Hufnagel** [comment]
ready to merge
