### ISSUE TITLE
Search field for words page

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#47]
## Value Proposition

**As a user**
**I want to filter my own vocabularies** 
**in order to find the one I want to edit** 
​

## Description
A search field is displayed at the top of the words page. This filters the displayed result.

​

## Acceptance Criteria

- [x] A search field at the top
- [x] A controlled input
- [x] Typing in the input field will filter the displayed result
      ​

## Tasks

- [x] create feature branch
- [x] write handler function that filters the array
- [x] use controlled inputs to trigger the handler function each time while typing
