### ISSUE TITLE
Display success

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#49]
## Value Proposition

**As a user** 
**I want to see my score (successful finished cards) on top of the page** 
**in order to be proud of my success** 
​

## Description

The amount of success is displayed
​

## Acceptance Criteria

- [x] In the header is an icon visible and the number of successful finished cards
      ​

## Tasks

- [x] create a feature branch
- [x] create a function that counts the number of successful finished cards
- [x] use this function to display the number in the header
- [x] do some styling to combine icon and number
