### ISSUE TITLE
US2: Render only 5 random cards

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#5]
## Value Proposition

**As a** user
**I want to**  see only 5 cards
**in order to** know what cards to train
​

## Description

​![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/138261b4-acc8-470b-b080-1980c7a61df6)

## Acceptance Criteria

- [x] Only 5 cards are rendered
- [x] The cards are chosen randomly (refresh makes new cards)
      ​

## Tasks

- [x] Create a feature-branch
- [x] Create a function getRandomCards()
- [x] Use that function to render the list
