### ISSUE TITLE
Refactor icon component

### ISSUE THREAD

**Issue by kai-franke** [Roland-Hufnagel/voc-trainer#53]
## Value Proposition

**As a** developer
**I want to** have a generic icon component
**in order to** be able to use and customize icons more easily. 
​

## Description

​

## Acceptance Criteria

- [ ] 
      ​

## Tasks

- [x] Create a feature branch
- [x] Create a `icons` variable, that is an object. Each element inside the object represents a single icon and contains an object with the following values: `title`, `viewBox`, `path`
- [x] Create an element within the new icon variable for each previously used icon component and copy the required values. If a previously used icon component consists of more than one path, change this by creating a compound path in a vector programm.
- [x] Create a single `Icon` component, that accepts the props `variant`, `size` and `color`. The `Icon` component returns a `<svg>`
- [ ] Use the new `Icon` component by replacing all occurrences of the previous icons in the entire project with this new component
