### ISSUE TITLE
US3: Show translation

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/voc-trainer#6]
## Value Proposition

**As a** user
**I want to** see the translation 
**in order to** check if I am right
​

## Description

![Image](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/78286b76-1d91-4423-892b-3281d36d86d5)

## Acceptance Criteria

- [x] Each card has an 'show answer' button
- [x] Clicking the button will display the translation
- [x] After clicking the button will disappear
      ​

## Tasks

- [x] Create a feature-branch
- [x] Create a Button Component
- [x] render the Button Component in the Card
- [x] Create a handleClick() function
- [x] Bind that function to the button
