### ISSUE TITLE
US4: Rate right answers

### ISSUE THREAD

**Issue by kai-franke** [Roland-Hufnagel/voc-trainer#8]
## Value Proposition

**As a** user
**I want to** rate my own answer
**in order to** get a feedback of my success.
​

## Description

![Screenshot 2023-07-28 at 18 32 01](https://github.com/Roland-Hufnagel/voc-trainer/assets/111574974/6862a774-4a0b-4f33-a1cd-7b929c898166)

​

## Acceptance Criteria

- [x] A 'right' and a 'wrong'-Button appear on the card when the answer is shown
- [x] Clicking the 'right'-Button will increase the count of right answers and will make the card smoothly disappear.
- [x] Clicking the 'wrong'-Button will make the card smoothly disappear.
- [x] The card disappears in a different way in order to the button I clicked.
- [x] The other cards will take the free place.
      ​

## Tasks

- [x] create a feature-branch
- [x] Add two buttons to the card-component (only shown when 'show answer' has been clicked)
- [x] create the function 'handleRight' which makes the card fade out in a 'lucky' way, that underlines the right answer.
- [x] create the function 'handleWrong' which makes the card fade out in a 'poor' way to visualize that the answer was wrong.
